spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo-db:27017/fitnessactivity?retryWrites=true&w=majority}
 
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

app:
  rabbitmq:
    exchange:
      name: fitness.exchange
    queue:
      name: activity.queue
    routing:
      key: activity.tracking