server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-16aa5adb-bhagyalakshmirbhagya1-b42d.k.aivencloud.com:15885/defaultdb?useSSL=true&requireSSL=true}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:your_aiven_password_here}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/